Update wechatpush-call

diff --git a/root/usr/libexec/wechatpush-call b/root/usr/libexec/wechatpush-call
--- a/root/usr/libexec/wechatpush-call
+++ b/root/usr/libexec/wechatpush-call
@@ -5,6 +5,18 @@ dir="/tmp/wechatpush" && mkdir -p "${dir}"
 oui_base="${dir}/oui_base.txt"
 oui_data=$(uci get wechatpush.config.oui_data 2>/dev/null)
 oui_url="https://standards-oui.ieee.org/oui/oui.txt"
+lang=$(uci -q get luci.main.lang || echo "zh-cn") 2>/dev/null
+
+translate() {
+	# 处理特殊字符
+	local lua_script=$(cat <<LUA
+	require "luci.i18n".setlanguage("$lang")
+	print(require "luci.i18n".translate([==[$1]==]))
+LUA
+	)
+
+	lua -e "$lua_script"
+}
 
 # 获取文件最后修改时间和行数
 file_date() {
@@ -51,18 +63,18 @@ download_file() {
 # 更新 MAC 信息文件
 down_oui() {
 	if [ -n "${oui_data}" ] && [ "${oui_data}" -ne "3" ]; then
-		echo "$(date "+%Y-%m-%d %H:%M:%S") 【info】开始后台更新 MAC 信息文件" >>"${logfile}"
+		echo "$(date "+%Y-%m-%d %H:%M:%S") [INFO] $(translate "Starting background update of MAC information file")" >>"${logfile}"
 		download_file "${oui_url}" "${dir}/oui.txt"
 		local RETVAL=$?
-		[ ${RETVAL} -ne 0 ] && echo "$(date "+%Y-%m-%d %H:%M:%S") 【!!!】设备 MAC 信息文件下载失败，返回码为 ${RETVAL}" >>"${logfile}" && return 1
-		echo "$(date "+%Y-%m-%d %H:%M:%S") 【info】设备 MAC 信息文件下载成功，处理中" >>"${logfile}"
+		[ ${RETVAL} -ne 0 ] && echo "$(date "+%Y-%m-%d %H:%M:%S") [ERROR] $(translate "Failed to download MAC information file, return code: ${RETVAL}")" >>"${logfile}" && return 1
+		echo "$(date "+%Y-%m-%d %H:%M:%S") [INFO] $(translate "MAC information file downloaded successfully, processing...")" >>"${logfile}"
 		if [ "${oui_data}" -eq "1" ]; then
 			grep -i -E ".*(base 16).*(apple|aruba|asus|autelan|belkin|bhu|buffalo|cctf|cisco|comba|datang|dell|dlink|dowell|ericsson|fast|feixun|fiberhome|fujitsu|grentech|h3c|hisense|hiwifi|honghai|honghao|hp|htc|huawei|intel|jinli|jse|lenovo|lg|liteon|malata|meizu|mercury|meru|moto|netcore|netgear|nokia|omron|oneplus|oppo|philips|router_unkown|samsung|shanzhai|sony|start_net|sunyuanda|tcl|tenda|texas|tianyu|tp-link|ubq|undefine|VMware|utstarcom|volans|xerox|xiaomi|zdc|zhongxing|smartisan).*" "${dir}/oui.txt" | sed -E 's/( Electronic| Technology| Intelligence| TECHNOLOGIES| Device| Systems| TELECOMMUNICATIONS| Instruments| Electronics| Corporation| Telecommunication| Communications| Electrical| Technology| Corporate| Intelligent| Interactive| MOBILE| Solutions| Mobility| Meraki| ELECTRO| VISUAL| Limited| International| Information| LLC|Co$|Co\.|Ltd\.$|Inc\.|B\.V\.$|AB$|,).*$/ /I; s/[[:space:]]*$//; s/ +$//' >"${oui_base}"
 		elif [ "${oui_data}" -eq "2" ]; then
 			grep -i "(base 16)" "${dir}/oui.txt" | sed -E 's/( Electronic| Technology| Intelligence| TECHNOLOGIES| Device| Systems| TELECOMMUNICATIONS| Instruments| Electronics| Corporation| Telecommunication| Communications| Electrical| Technology| Corporate| Intelligent| Interactive| MOBILE| Solutions| Mobility| Meraki| ELECTRO| VISUAL| Limited| International| Information| LLC|Co$|Co\.|Ltd\.$|Inc\.|B\.V\.$|AB$|,).*$/ /I; s/[[:space:]]*$//; s/ +$//' >"${oui_base}"
 		fi
 		rm -f "${dir}/oui.txt" >/dev/null 2>&1
-		echo "$(date "+%Y-%m-%d %H:%M:%S") 【info】设备 MAC 信息文件处理完成" >>"${logfile}"
+		echo "$(date "+%Y-%m-%d %H:%M:%S") [INFO] $(translate "MAC information file processing completed")" >>"${logfile}"
 	fi
 }
 
@@ -71,7 +83,7 @@ if [ "$1" == "clear_log" ]; then
 	>"${logfile}"
 elif [ "$1" == "down_oui" ]; then
 	# 更新 MAC 信息列表
-	[ $(file_date "$oui_base") -lt 604800 ] && echo "$(date "+%Y-%m-%d %H:%M:%S") 【info】MAC 信息文件无需更新" >>"${logfile}" && exit 2
+	[ $(file_date "$oui_base") -lt 604800 ] && echo "$(date "+%Y-%m-%d %H:%M:%S") [INFO] $(translate "MAC information file does not need updating")" >>"${logfile}" && exit 2
 	down_oui >/dev/null 2>&1 &
 elif [ "$1" == "child" ]; then
 	shift
